### ISSUE TITLE
Question: Avoiding error identifier has already been declared 

### ISSUE THREAD

**Issue by jmatsushita** [n-riesco/ijavascript#107] opened 2017-06-05 16:17 UTC
![image](https://cloud.githubusercontent.com/assets/356097/26792303/41d8f6c4-4a1a-11e7-947b-38bddd5d938b.png)

What's the elegant way to avoid having these popping up? The ways I know work are:
 - Restart the kernel.
 - Just clearing the output and pretend it didn't happen

The way I tried which didn't work for me are:
 - Avoid restarting all
 - Avoid restarting cells with const in it
 - Not use const

:)

**Comment by n-riesco** [comment] 2017-06-08 13:53
First of all, I have to say this is the expected behaviour: `const` was introduced in JS to ensure a variable doesn't get reassigned (Note that, similarly, `let` doesn't allow the re-declaration of a variable). The use of `const` or `let` inside the global scope will prevent you from re-running a cell (unless the kernel session is restarted).

---

Since IJavascript is a JS kernel and `const` is part of JS, I think a kernel like [jp-babel](https://github.com/n-riesco/jp-babel) would be a more suitable kernel for the needs I can infer from your post.

I imagine one could write a plugin that replaces all `const`'s and `let`'s in the global scope by `var`'s, so that no exceptions is thrown when a cell is re-run without restarting the kernel session.

---

Out of curiosity: you say that *"Not use const"* *"didn't work for you"*. Why was that?

**Closed by n-riesco** 2017-06-08 13:53 UTC

**Comment by n-riesco** [comment] 2017-06-08 13:54
I'm closing the issue, but, please,  feel free to continue the discussion here.

**Comment by Nithanaroy** [comment] 2020-08-21 00:19
`const` makes sense. But I would use redefine a class interactively making changes. How can we achieve that?
In Scala kernel, rerunning a cell say with `val a = 10` doesn't throw any error, but instead overrides it. But of course if we try `a = 20` later it complains as expected. Can this behavior be achieved?
