### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Slyke** [n-riesco/ijavascript#287] opened 2024-02-22 09:42 UTC
Trying to `import { Ollama } from "langchain/llms/ollama";`

But getting:
```
evalmachine.<anonymous>:1
import { Ollama } from "langchain/llms/ollama";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:99:7)
    at createScript (node:vm:255:10)
    at Object.runInThisContext (node:vm:303:10)
    at run ([eval]:1020:15)
    at onRunRequest ([eval]:864:18)
    at onMessage ([eval]:828:13)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
 ```
    
I'm running vscode in Windows, with Jupyter running in WSL2. It's execiting NodeJS `v20.11.0`. I'm fairly certain I set everything up correctly, but probably missed something.

![image](https://github.com/n-riesco/ijavascript/assets/6442613/aa2ed356-05c6-415e-99f8-527f4a0278f3)

**Comment by n-riesco** [comment] 2024-02-24 11:37
Node.js doesn't allow the use of `import` in a REPL session. See https://github.com/n-riesco/ijavascript/issues/210 and https://github.com/n-riesco/ijavascript/issues/210#issuecomment-974713806 for more context.

**Comment by n-riesco** [comment] 2024-03-26 22:33
Closing as duplicate of #210

**Closed as completed by n-riesco** 2024-03-26 22:33 UTC
