### ISSUE TITLE
Cannot install ijavascript with Visual Studio Community 2022

### ISSUE THREAD

**Issue by ENIAC-6** [n-riesco/ijavascript#261] opened 2021-12-27 21:32 UTC
I am using conda 3.7.0 and python 3.7.0. I also installed Visual Studio Community 2022. I cannot install ijavascript. In the error I receive below, I see it says it is looking for VS2017 and that an undefined version was found. Is there a specific version of VS that I need to download? And do I need to save it to somewhere specific? I had a .ipynb file that used to run on an old computer (with ijavascript) that I would like to use on a new computer. I have read all of the related issues but cannot solve this. Any suggestions would be greatly appreciated.

Running conda install nodejs worked, however when I try to run npm install -g ijavascript, (after ) I get the following errors:

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\ijavascript\node_modules\zeromq
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node-gyp-build || npm run build:libzmq
npm ERR! > zeromq@5.2.8 build:libzmq
npm ERR! > node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.0 found at "C:\Users\myProfile\AppData\Local\Continuum\anaconda3\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2017
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS checking VS2019 (16.11.32002.261) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - found VC++ toolset: v142
npm ERR! gyp ERR! find VS - found Windows SDK: 10.0.19041.0
npm ERR! gyp ERR! find VS - msvs_version does not match this version
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS - "2019"
npm ERR! gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Users\\myProfile\\AppData\\Local\\Continuum\\anaconda3\\node.exe" "C:\\Users\\myProfile\\AppData\\Local\\Continuum\\anaconda3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\ijavascript\node_modules\zeromq
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.0 found at "C:\Users\myProfile\AppData\Local\Continuum\anaconda3\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2017
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS checking VS2019 (16.11.32002.261) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - found VC++ toolset: v142
npm ERR! gyp ERR! find VS - found Windows SDK: 10.0.19041.0
npm ERR! gyp ERR! find VS - msvs_version does not match this version
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS - "2019"
npm ERR! gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Users\\myProfile\\AppData\\Local\\Continuum\\anaconda3\\node.exe" "C:\\Users\\myProfile\\AppData\\Local\\Continuum\\anaconda3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\myProfile\AppData\Local\Continuum\anaconda3\node_modules\ijavascript\node_modules\zeromq
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myProfile\AppData\Local\npm-cache\_logs\2021-12-27T19_27_24_417Z-debug.log

**Comment by n-riesco** [comment] 2021-12-28 13:52
This is an ongoing issue with one of the dependencies of ijavascript ([zeromq](https://github.com/zeromq/zeromq.js/tree/5.x)).

Unfortunately, no prebuilt binaries for node v16 have been published yet (see https://github.com/zeromq/zeromq.js/issues/495 ).

This issue has already been reported in #253 (but no successful workarounds have been found yet).

In the meantime, downgrading to node.js v14 or v15 may fix the issue for windows users. 


---

I'm closing this issue as is a duplicate of #253

**Comment by ENIAC-6** [comment] 2021-12-28 16:28
@n-riesco  thanks much for the quick reply. Downloading [Visual Studio 2019](url) fixed the issue on two computers for me.

**Comment by n-riesco** [comment] 2021-12-29 16:07
@ENIAC-6 Thank you for reporting back. Just to confirm it's working for you with Node.js v16 and VS2019?

**Comment by ENIAC-6** [comment] 2021-12-29 16:44
@n-riesco Correct, I have Node.js v16.13.1 with Visual Studio 2019. Thanks again-- really appreciate ijavascript.

**Comment by APerricone** [comment] 2022-03-09 04:31
So, this is closed installing Visual studio 2019? I don't think it is the a solution, I already have VS2022, I must install 2 visual studios?

**Closed** 2022-03-09 11:58 UTC
