### ISSUE TITLE
Noob question: `Cannot use import statement outside a module` when trying to use an external module

### ISSUE THREAD

**Issue by brunetton** [n-riesco/ijavascript#239] opened 2021-04-26 17:14 UTC
Hi

Sorry for this noob question but I'm kind of stuck here: is it possible to import external node modules ?

I tried to install and use a node module, but trying to import it on ijsnotebook:

```
> import { Gitlab } from '@gitbeaker/node';

evalmachine.<anonymous>:1
import { Gitlab } from '@gitbeaker/node';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:100:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at run ([eval]:1054:15)
    at onRunRequest ([eval]:888:18)
    at onMessage ([eval]:848:13)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

I surely missed something but this could be useful for others

**Comment by n-riesco** [comment] 2021-04-27 12:30
The error you see is the same error you'd see if you try to run import in a Node.js CLI session. For more info, see related issues: #210 #213 #215

Alternatives to a static import:
* an ES5 import: `var { Gitlab } = require('@gitbeaker/node');`
* [a dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports): `import('@gitbeaker/node').then((module) => {global.Gitlab = module.Gitlab});`

Closing as duplicate of #210

**Closed by n-riesco** 2021-04-27 12:30 UTC

**Comment by brunetton** [comment] 2021-05-13 10:38
Thanks for your answer and sorry for the noise

**Comment by prothSFDC** [comment] 2023-03-07 16:54
THANK YOU @n-riesco for looking into this
I saw your comment here: https://github.com/n-riesco/ijavascript/issues/210#issuecomment-1458474048

I was nearly giddy with having a recent version of d3 working.

I'll keep testing, but it gave hope that it isn't insurmountable
- and greatly greatly appreciated.
