### ISSUE TITLE
Support for iojs?

### ISSUE THREAD

**Issue by jakubholynet** [n-riesco/ijavascript#39] opened 2015-08-11 19:56 UTC
I have tried to install `ijs` with iojs 3.0.0 but it doesn't seem to be working (namely compilation of zmq fails with errors such as

> no viable conversion from      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'

It would be great to be able to use iojs and thus ES6.

Thank you!

**Comment by jakubholynet** [comment] 2015-08-14 13:12
See https://github.com/node-inspector/node-inspector/issues/523 for the same issue with node-inspector

**Comment by n-riesco** [comment] 2015-08-19 16:33
[This comment](https://github.com/nodejs/iojs.org/issues/420#issuecomment-127842470) makes me think the issue is caused by an API change in V8.

I have opened [an issue](https://github.com/JustinTulloss/zeromq.node/issues/447) on the `zeromq.node` repository.

**Comment by rgbkrk** [comment] 2015-08-19 17:22
Yeah I've been using iojs with ijavascript for some time. I've continually had issues with nan, node-gyp, and node-zmq - we need to help get that house in order (it's even worse in Electron/Atom land).

**Comment by n-riesco** [comment] 2015-08-27 21:27
The fix for zeromq.node has already been [released](https://github.com/JustinTulloss/zeromq.node/issues/447).

I've tested IJavascript on the lastest Docker image and it passes my tests. I will close this issue now. 

@jakubholynet , please re-open the issue, if you still see this problem.

**Closed by n-riesco** 2015-08-27 21:27 UTC
Labels: bug, help wanted
