### ISSUE TITLE
Add support for bash commands

### ISSUE THREAD

**Issue by cawoodm** [n-riesco/ijavascript#262] opened 2021-12-30 19:39 UTC
With the Python Core/Kernel it's possible to run bash commands by prepending a `!`:
```
!echo "Hello World!"
```

This would be a great feature to add to this core and, I guess, a fairly simple improvement.

**Comment by n-riesco** [comment] 2021-12-31 18:51
The operator `!` already exists in Javascript.
See #43 for more context.
If you still want to tread that path, see [magicpatch](https://github.com/n-riesco/ijavascript/issues/43#issuecomment-753674716).

Closing as duplicate of #43.

**Closed by n-riesco** 2021-12-31 18:51 UTC
